name: "Tg Bot for HomeAssistant"
description: "testing version. just 2 webhooks"
version: "1.0.1"
slug: "tg_bot_testing"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  bot_id: ""
  admin_id: 0
  group_id: ""
  webhook_id_1: ""
  webhook_id_2: ""
schema:
  bot_id: str
  admin_id: int
  group_id: str
  webhook_id_1: str
  webhook_id_2: str